FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=mysqlpassword
ENV MYSQL_DATABASE=database
ENV MYSQL_USER=mysqlusername
ENV MYSQL_PASSWORD=mysqlpassword

# Copy database initialization scripts
COPY init.sql /docker-entrypoint-initdb.d/